<?php
/**
 * @file
 * Code for the CuLaw Paragraphs feature.
 */

include_once 'culaw_paragraphs.features.inc';

function culaw_paragraphs_block_info() {
    $blocks = array();
    $blocks['secondary_navigation'] = array(
        'info' => t('Secondary Navigation'),
    );

    return $blocks;
}

function culaw_paragraphs_block_view($delta='') {
    $block = array();

    switch($delta) {
        case 'secondary_navigation' :
            $block['content'] = culaw_paragraphs_render_menu('main-menu','secondary-nav');
            break;
    }

    return $block;
}

function culaw_paragraphs_preprocess_entity(&$variables) {
    if ($variables['entity_type'] == 'paragraphs_item') {
        $bundle_type = $variables['paragraphs_item']->bundle;
        switch ($bundle_type) {
            case 'layout_row':
                //dpm($variables);
                if (isset($variables['id'])) {
                    $variables['content']['row_id'] = array("#type"=>'field','#value'=>$variables['id']);
                }
                break;
            case 'quick_links_card':
            case 'section_navigation_card':
                //get parent headline
                $parent_bundle = $variables['paragraphs_item']->hostEntity();
                if(isset($parent_bundle->field_headline['und'][0])) {
                    $headline = $parent_bundle->field_headline['und'][0]['value'];
                    $variables['content']['field_headline'] = $headline;
                }
                break;
            case 'media_card':
            case 'cta_card':
                $parent_bundle = $variables['paragraphs_item']->hostEntity();
                if ($parent_bundle->field_cta_options['und'][0]['value'] == 'banner') {
                    //set variable to tell the banner that this row is a nav or text
                    //load next bundle in node to see what it is ... navigation or not
                    $parent_node = $parent_bundle->hostEntity();
                    foreach($parent_node->field_content_rows['und'] AS $key => $value) {
                        if (isset($banner_element)) {
                            $entities = entity_load('paragraphs_item', array($value['value']));
                            if (count($entities)) {
                                $entity = array_pop($entities);
                                if ($entity) {
                                    if ($entity->bundle == 'layout_row') {
                                        $variables['content']['background_color'] = 'cta';
                                    }
                                }
                            }
                            break;
                        }
                        if ($value['value'] == $parent_bundle->item_id) {
                            $banner_element = true;
                        }
                    }
                }
                switch (count($parent_bundle->field_card_options['und'])) {
                    //add style option for single so the media card knows how many are in the row
                    case 1:
                        $variables['content']['single_item'] = TRUE;
                        break;
                    case 2:
                        break;
                }

                $variables['content']['style_option'] = culaw_paragraphs_format_class($parent_bundle->field_cta_options['und'][0]['value']);
                break;
            case 'social_media_card':

                drupal_add_css("https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", 'external');
                drupal_add_js(drupal_get_path('module', 'culaw_paragraphs') . '/js/jquery.socialfeed/codebird.js', array('type' => 'file', 'group' => JS_THEME));
                drupal_add_js(drupal_get_path('module', 'culaw_paragraphs') . '/js/jquery.socialfeed/doT.min.js', array('type' => 'file', 'group' => JS_THEME));
                drupal_add_js(drupal_get_path('module', 'culaw_paragraphs') . '/js/jquery.socialfeed/moment.min.js', array('type' => 'file', 'group' => JS_THEME));
                drupal_add_js(drupal_get_path('module', 'culaw_paragraphs') . '/js/jquery.socialfeed/jquery.socialfeed.js', array('type' => 'file', 'group' => JS_THEME));
                drupal_add_js(drupal_get_path('module', 'culaw_paragraphs') . '/js/jquery.socialfeed/init.js', array('type' => 'file', 'group' => JS_THEME));

                $content_array = array();

                $content_array['field_twitter_query'] = isset($variables['content']['field_twitter_query']['#items'][0]['value']) ? $variables['content']['field_twitter_query']['#items'][0]['value'] : "";
                $content_array['field_twitter_key'] = isset($variables['content']['field_twitter_key']['#items'][0]['value']) ? $variables['content']['field_twitter_key']['#items'][0]['value'] : "";
                $content_array['field_twitter_secret'] = isset($variables['content']['field_twitter_secret']['#items'][0]['value']) ? $variables['content']['field_twitter_secret']['#items'][0]['value'] : "";
                $content_array['field_twitter_limit'] = isset($variables['content']['field_twitter_limit']['#items'][0]['value']) ? $variables['content']['field_twitter_limit']['#items'][0]['value'] : "";

                $content_array['field_instagram_query'] = isset($variables['content']['field_instagram_query']['#items'][0]['value']) ? $variables['content']['field_instagram_query']['#items'][0]['value'] : "";
                $content_array['field_instagram_client_id'] = isset($variables['content']['field_instagram_client_id']['#items'][0]['value']) ? $variables['content']['field_instagram_client_id']['#items'][0]['value'] : "";
                $content_array['field_instagram_token'] = isset($variables['content']['field_instagram_token']['#items'][0]['value']) ? $variables['content']['field_instagram_token']['#items'][0]['value'] : "";
                $content_array['field_instagram_limit'] = isset($variables['content']['field_instagram_limit']['#items'][0]['value']) ? $variables['content']['field_instagram_limit']['#items'][0]['value'] : "";

                $content_array['field_facebook_query'] = isset($variables['content']['field_facebook_query']['#items'][0]['value']) ? $variables['content']['field_facebook_query']['#items'][0]['value'] : "";
                $content_array['field_facebook_token'] = isset($variables['content']['field_facebook_token']['#items'][0]['value']) ? $variables['content']['field_facebook_token']['#items'][0]['value'] : "";
                $content_array['field_facebook_limit'] = isset($variables['content']['field_facebook_limit']['#items'][0]['value']) ? $variables['content']['field_facebook_limit']['#items'][0]['value'] : "";

                $variables['content'] = $content_array;
                break;
            default;
                //print $variables['paragraphs_item']->bundle ;
                break;
        }
    }
}

function culaw_paragraphs_render_menu($menu, $style = null) {
    $output = "";
    $menuItems = menu_tree_page_data($menu);

    //deprecated
    if (isset($style)) {
        $current_leaf = menu_link_get_preferred(current_path());
        $parameters = array(
            'active_trail' => array($current_leaf['plid']),
            'only_active_trail' => FALSE,
            'min_depth' => $current_leaf['depth']+1,
            'max_depth' => $current_leaf['depth']+1,
            'conditions' => array('plid' => $current_leaf['mlid']),
        );
        $menuItems = menu_build_tree($current_leaf['menu_name'], $parameters);
    }


    foreach ($menuItems as $key => $m) {
        if ($m['link']['in_active_trail'] && $menuItems[$key]['below']) {
            if (isset($m['below'])) {
                $parent_key = $key;
                $tree_output = menu_tree_output($menuItems[$key]['below']);

                $links = array();
                foreach($tree_output AS $key => $value) {
                    if (is_numeric($key)) {
                        $links[] = array(
                            "title"=>$value['#title'],
                            "href"=>$value['#href'],
                            "attributes" => $value['#attributes']
                        );
                    }
                }
                if (isset($style)) {
                    switch($style) {
                        case 'secondary-nav':
                            //culaw_secondary_menu
                            return theme('links', array('heading'=> $parent_key, 'links' => $links));
                            break;
                    }
                } else {
                    $groups = array_chunk($links, (int)ceil(count($links) / 3));
                    $output = "";
                    foreach ($groups AS $key => $value) {
                        $output .= '<div class="col-sm-4 col-xs-12 same-height">' . theme('links', array('links' => $value, 'attributes' => array('class' => array('subnavigation-wrap__subnavigation-links', 'list-unstyled')), 'header' => array('text' => t('Main menu'), 'level' => 'h2', 'class' => array('element-invisible')))) . '</div>';
                    }
                }
            }
        }
    }
    print $output;
}

function culaw_paragraphs_format_class($var) {
    return str_replace(" ","-",strtolower($var));
}

//from paragraph template files
function _culaw_paragraphs_format_content($id, $format) {
    $node = node_load($id);
    switch($format) {
        case 'news_feed_row':
            $date = $node->created;
            //cls_mcl_event_datetime
            //$node->created
            break;
        case 'event_feed_row':
            $date = strtotime($node->field_event_date['und'][0]['value']);
            $today = time();
            if ($date < $today) {
                $date = $today;
            }
            //if start date is less than today, set to today. this means it spans several days and today is one of those days
            break;
        default:
            break;
    }
    $summary = "";
    if (isset($node->field_event_description['und'])) {
        $summary = $node->field_event_description['und'][0]['safe_summary'] != "" ? $node->field_event_description['und'][0]['safe_summary'] : strip_tags($node->field_event_description['und'][0]['safe_value']);
    }
    $date_array = array(
        'month' => date("M",$date),
        'day' => date("j",$date),
        'class' => date("Y-m-d",$date),
        'date' => date("F dS, Y",$date)
    );
    $row = array(
        'category' => 'News',
        'summary' => $summary,
        'date' => $date_array,
        'source' => $node->title,
        'url' => "/node/" . $node->nid
    );
    return $row;
}