<?php

$view = new view();
$view->name = 'cls_aces2_applicants';
$view->description = '';
$view->tag = 'default';
$view->base_table = 'cls_aces2_applicant';
$view->human_name = 'Applicants';
$view->core = 7;
$view->api_version = '3.0';
$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

/* Display: Master */
$handler = $view->new_display('default', 'Master', 'default');
$handler->display->display_options['title'] = 'Applicants';
$handler->display->display_options['use_more_always'] = FALSE;
$handler->display->display_options['access']['type'] = 'perm';
$handler->display->display_options['access']['perm'] = 'manage cls_aces applicants';
$handler->display->display_options['cache']['type'] = 'none';
$handler->display->display_options['query']['type'] = 'views_query';
$handler->display->display_options['query']['options']['query_comment'] = FALSE;
$handler->display->display_options['exposed_form']['type'] = 'basic';
$handler->display->display_options['pager']['type'] = 'full';
$handler->display->display_options['pager']['options']['items_per_page'] = '50';
$handler->display->display_options['style_plugin'] = 'table';
$handler->display->display_options['style_options']['columns'] = array(
  'id' => 'id',
  'year_entering' => 'year_entering',
  'lsac_account_number' => 'lsac_account_number',
  'last_name' => 'last_name',
  'first_name' => 'first_name',
  'nothing' => 'nothing',
);
$handler->display->display_options['style_options']['default'] = 'last_name';
$handler->display->display_options['style_options']['info'] = array(
  'id' => array(
    'sortable' => 0,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'year_entering' => array(
    'sortable' => 1,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'lsac_account_number' => array(
    'sortable' => 1,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'last_name' => array(
    'sortable' => 1,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'first_name' => array(
    'sortable' => 1,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'nothing' => array(
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
);
$handler->display->display_options['style_options']['override'] = FALSE;
$handler->display->display_options['style_options']['sticky'] = TRUE;
/* Field: Applicant: Applicant ID */
$handler->display->display_options['fields']['id']['id'] = 'id';
$handler->display->display_options['fields']['id']['table'] = 'cls_aces2_applicant';
$handler->display->display_options['fields']['id']['field'] = 'id';
$handler->display->display_options['fields']['id']['label'] = '';
$handler->display->display_options['fields']['id']['exclude'] = TRUE;
$handler->display->display_options['fields']['id']['element_label_colon'] = FALSE;
$handler->display->display_options['fields']['id']['separator'] = '';
/* Field: Applicant: Program_applied */
$handler->display->display_options['fields']['program_applied']['id'] = 'program_applied';
$handler->display->display_options['fields']['program_applied']['table'] = 'cls_aces2_applicant';
$handler->display->display_options['fields']['program_applied']['field'] = 'program_applied';
$handler->display->display_options['fields']['program_applied']['label'] = 'Applied Program';
$handler->display->display_options['fields']['program_applied']['separator'] = '';
/* Field: Applicant: Year_entering */
$handler->display->display_options['fields']['year_entering']['id'] = 'year_entering';
$handler->display->display_options['fields']['year_entering']['table'] = 'cls_aces2_applicant';
$handler->display->display_options['fields']['year_entering']['field'] = 'year_entering';
$handler->display->display_options['fields']['year_entering']['separator'] = '';
/* Field: Applicant: Lsac_account_number */
$handler->display->display_options['fields']['lsac_account_number']['id'] = 'lsac_account_number';
$handler->display->display_options['fields']['lsac_account_number']['table'] = 'cls_aces2_applicant';
$handler->display->display_options['fields']['lsac_account_number']['field'] = 'lsac_account_number';
$handler->display->display_options['fields']['lsac_account_number']['label'] = 'LSAC Account Number';
/* Field: Applicant: Last_name */
$handler->display->display_options['fields']['last_name']['id'] = 'last_name';
$handler->display->display_options['fields']['last_name']['table'] = 'cls_aces2_applicant';
$handler->display->display_options['fields']['last_name']['field'] = 'last_name';
$handler->display->display_options['fields']['last_name']['label'] = 'Last Name';
/* Field: Applicant: First_name */
$handler->display->display_options['fields']['first_name']['id'] = 'first_name';
$handler->display->display_options['fields']['first_name']['table'] = 'cls_aces2_applicant';
$handler->display->display_options['fields']['first_name']['field'] = 'first_name';
$handler->display->display_options['fields']['first_name']['label'] = 'First Name';
/* Field: Global: Custom text */
$handler->display->display_options['fields']['nothing']['id'] = 'nothing';
$handler->display->display_options['fields']['nothing']['table'] = 'views';
$handler->display->display_options['fields']['nothing']['field'] = 'nothing';
$handler->display->display_options['fields']['nothing']['label'] = 'View';
$handler->display->display_options['fields']['nothing']['alter']['text'] = 'View';
$handler->display->display_options['fields']['nothing']['alter']['make_link'] = TRUE;
$handler->display->display_options['fields']['nothing']['alter']['path'] = 'admissions/admin/applicants/[id]';
$handler->display->display_options['fields']['nothing']['hide_alter_empty'] = TRUE;
/* Sort criterion: Applicant: Last_name */
$handler->display->display_options['sorts']['last_name']['id'] = 'last_name';
$handler->display->display_options['sorts']['last_name']['table'] = 'cls_aces2_applicant';
$handler->display->display_options['sorts']['last_name']['field'] = 'last_name';
/* Sort criterion: Applicant: First_name */
$handler->display->display_options['sorts']['first_name']['id'] = 'first_name';
$handler->display->display_options['sorts']['first_name']['table'] = 'cls_aces2_applicant';
$handler->display->display_options['sorts']['first_name']['field'] = 'first_name';
/* Filter criterion: Applicant: Year_entering */
$handler->display->display_options['filters']['year_entering']['id'] = 'year_entering';
$handler->display->display_options['filters']['year_entering']['table'] = 'cls_aces2_applicant';
$handler->display->display_options['filters']['year_entering']['field'] = 'year_entering';
$handler->display->display_options['filters']['year_entering']['value']['value'] = '2014';
$handler->display->display_options['filters']['year_entering']['group'] = 1;
$handler->display->display_options['filters']['year_entering']['exposed'] = TRUE;
$handler->display->display_options['filters']['year_entering']['expose']['operator_id'] = 'year_entering_op';
$handler->display->display_options['filters']['year_entering']['expose']['label'] = 'Year Entering';
$handler->display->display_options['filters']['year_entering']['expose']['operator'] = 'year_entering_op';
$handler->display->display_options['filters']['year_entering']['expose']['identifier'] = 'year_entering';
$handler->display->display_options['filters']['year_entering']['expose']['remember_roles'] = array(
  2 => '2',
  1 => 0,
  157 => 0,
  149 => 0,
  58 => 0,
  63 => 0,
  64 => 0,
  26 => 0,
  25 => 0,
  139 => 0,
  32 => 0,
  145 => 0,
  62 => 0,
  185 => 0,
  4 => 0,
  5 => 0,
  120 => 0,
  70 => 0,
  189 => 0,
  148 => 0,
  159 => 0,
  57 => 0,
  88 => 0,
  178 => 0,
  105 => 0,
  201 => 0,
  47 => 0,
  183 => 0,
  160 => 0,
  187 => 0,
  37 => 0,
  22 => 0,
  123 => 0,
  71 => 0,
  94 => 0,
  92 => 0,
  116 => 0,
  165 => 0,
  144 => 0,
  173 => 0,
  192 => 0,
  166 => 0,
  191 => 0,
  194 => 0,
  188 => 0,
  130 => 0,
  78 => 0,
  55 => 0,
  91 => 0,
  77 => 0,
  93 => 0,
  164 => 0,
  79 => 0,
  195 => 0,
  143 => 0,
  106 => 0,
  53 => 0,
  119 => 0,
  69 => 0,
  90 => 0,
  86 => 0,
  103 => 0,
  108 => 0,
  80 => 0,
  121 => 0,
  110 => 0,
  196 => 0,
  109 => 0,
  35 => 0,
  101 => 0,
  83 => 0,
  89 => 0,
  59 => 0,
  100 => 0,
  158 => 0,
  72 => 0,
  186 => 0,
  48 => 0,
  135 => 0,
  174 => 0,
  137 => 0,
  76 => 0,
  190 => 0,
  104 => 0,
  75 => 0,
  74 => 0,
  167 => 0,
  197 => 0,
  198 => 0,
  134 => 0,
  111 => 0,
  175 => 0,
  176 => 0,
  177 => 0,
  122 => 0,
  42 => 0,
  133 => 0,
  102 => 0,
  117 => 0,
  118 => 0,
  23 => 0,
  41 => 0,
  193 => 0,
  40 => 0,
  27 => 0,
  3 => 0,
  28 => 0,
  29 => 0,
  20 => 0,
  8 => 0,
  12 => 0,
  7 => 0,
  13 => 0,
  18 => 0,
  10 => 0,
  15 => 0,
  11 => 0,
  16 => 0,
  14 => 0,
  19 => 0,
  17 => 0,
  9 => 0,
  6 => 0,
  24 => 0,
  21 => 0,
  31 => 0,
  33 => 0,
  34 => 0,
  36 => 0,
  30 => 0,
  38 => 0,
  39 => 0,
  43 => 0,
  44 => 0,
  45 => 0,
  46 => 0,
  49 => 0,
  50 => 0,
  51 => 0,
  52 => 0,
  54 => 0,
  56 => 0,
  60 => 0,
  61 => 0,
  65 => 0,
  66 => 0,
  67 => 0,
  68 => 0,
  73 => 0,
  84 => 0,
  85 => 0,
  87 => 0,
  95 => 0,
  96 => 0,
  97 => 0,
  98 => 0,
  99 => 0,
  112 => 0,
  113 => 0,
  114 => 0,
  115 => 0,
  124 => 0,
  125 => 0,
  126 => 0,
  127 => 0,
  128 => 0,
  129 => 0,
  131 => 0,
  132 => 0,
  136 => 0,
  138 => 0,
  140 => 0,
  141 => 0,
  142 => 0,
  146 => 0,
  147 => 0,
  150 => 0,
  151 => 0,
  152 => 0,
  153 => 0,
  154 => 0,
  155 => 0,
  156 => 0,
  161 => 0,
  162 => 0,
  163 => 0,
  168 => 0,
  169 => 0,
  170 => 0,
  171 => 0,
  172 => 0,
  179 => 0,
  180 => 0,
  181 => 0,
  182 => 0,
  184 => 0,
  199 => 0,
  200 => 0,
);
/* Filter criterion: Applicant: Program_applied */
$handler->display->display_options['filters']['program_applied']['id'] = 'program_applied';
$handler->display->display_options['filters']['program_applied']['table'] = 'cls_aces2_applicant';
$handler->display->display_options['filters']['program_applied']['field'] = 'program_applied';
$handler->display->display_options['filters']['program_applied']['group'] = 1;
$handler->display->display_options['filters']['program_applied']['exposed'] = TRUE;
$handler->display->display_options['filters']['program_applied']['expose']['operator_id'] = 'program_applied_op';
$handler->display->display_options['filters']['program_applied']['expose']['label'] = 'Program_applied';
$handler->display->display_options['filters']['program_applied']['expose']['operator'] = 'program_applied_op';
$handler->display->display_options['filters']['program_applied']['expose']['identifier'] = 'program_applied';
$handler->display->display_options['filters']['program_applied']['expose']['multiple'] = TRUE;
$handler->display->display_options['filters']['program_applied']['is_grouped'] = TRUE;
$handler->display->display_options['filters']['program_applied']['group_info']['label'] = 'Applied Program';
$handler->display->display_options['filters']['program_applied']['group_info']['identifier'] = 'program_applied';
$handler->display->display_options['filters']['program_applied']['group_info']['widget'] = 'radios';
$handler->display->display_options['filters']['program_applied']['group_info']['multiple'] = TRUE;
$handler->display->display_options['filters']['program_applied']['group_info']['default_group_multiple'] = array(
  1 => '1',
  2 => '2',
  3 => '3',
);
$handler->display->display_options['filters']['program_applied']['group_info']['group_items'] = array(
  1 => array(
    'title' => 'J.D. (1)',
    'operator' => '=',
    'value' => array(
      'value' => '1',
      'min' => '',
      'max' => '',
    ),
  ),
  2 => array(
    'title' => 'LL.M. (2)',
    'operator' => '=',
    'value' => array(
      'value' => '2',
      'min' => '',
      'max' => '',
    ),
  ),
  3 => array(
    'title' => 'J.S.D. (3)',
    'operator' => '=',
    'value' => array(
      'value' => '3',
      'min' => '',
      'max' => '',
    ),
  ),
);
/* Filter criterion: Applicant: Lsac_account_number */
$handler->display->display_options['filters']['lsac_account_number']['id'] = 'lsac_account_number';
$handler->display->display_options['filters']['lsac_account_number']['table'] = 'cls_aces2_applicant';
$handler->display->display_options['filters']['lsac_account_number']['field'] = 'lsac_account_number';
$handler->display->display_options['filters']['lsac_account_number']['group'] = 1;
$handler->display->display_options['filters']['lsac_account_number']['exposed'] = TRUE;
$handler->display->display_options['filters']['lsac_account_number']['expose']['operator_id'] = 'lsac_account_number_op';
$handler->display->display_options['filters']['lsac_account_number']['expose']['label'] = 'LSAC Account No.';
$handler->display->display_options['filters']['lsac_account_number']['expose']['operator'] = 'lsac_account_number_op';
$handler->display->display_options['filters']['lsac_account_number']['expose']['identifier'] = 'lsac_account_number';
/* Filter criterion: Applicant: First_name */
$handler->display->display_options['filters']['first_name']['id'] = 'first_name';
$handler->display->display_options['filters']['first_name']['table'] = 'cls_aces2_applicant';
$handler->display->display_options['filters']['first_name']['field'] = 'first_name';
$handler->display->display_options['filters']['first_name']['operator'] = 'starts';
$handler->display->display_options['filters']['first_name']['group'] = 1;
$handler->display->display_options['filters']['first_name']['exposed'] = TRUE;
$handler->display->display_options['filters']['first_name']['expose']['operator_id'] = 'first_name_op';
$handler->display->display_options['filters']['first_name']['expose']['label'] = 'First Name';
$handler->display->display_options['filters']['first_name']['expose']['use_operator'] = TRUE;
$handler->display->display_options['filters']['first_name']['expose']['operator'] = 'first_name_op';
$handler->display->display_options['filters']['first_name']['expose']['identifier'] = 'first_name';
/* Filter criterion: Applicant: Last_name */
$handler->display->display_options['filters']['last_name']['id'] = 'last_name';
$handler->display->display_options['filters']['last_name']['table'] = 'cls_aces2_applicant';
$handler->display->display_options['filters']['last_name']['field'] = 'last_name';
$handler->display->display_options['filters']['last_name']['operator'] = 'starts';
$handler->display->display_options['filters']['last_name']['group'] = 1;
$handler->display->display_options['filters']['last_name']['exposed'] = TRUE;
$handler->display->display_options['filters']['last_name']['expose']['operator_id'] = 'last_name_op';
$handler->display->display_options['filters']['last_name']['expose']['label'] = 'Last Name';
$handler->display->display_options['filters']['last_name']['expose']['use_operator'] = TRUE;
$handler->display->display_options['filters']['last_name']['expose']['operator'] = 'last_name_op';
$handler->display->display_options['filters']['last_name']['expose']['identifier'] = 'last_name';

/* Display: Page */
$handler = $view->new_display('page', 'Page', 'page');
$handler->display->display_options['path'] = 'admissions/admin/applicants';
$handler->display->display_options['menu']['type'] = 'normal';
$handler->display->display_options['menu']['title'] = 'Applicants';
$handler->display->display_options['menu']['weight'] = '0';
